Some progress, but it breaks with message:
2019-04-05 18:38:03,268 - DEBUG - f.futawilly.py - ln.281 - update_thread() currently testing post_num=16313827
2019-04-05 18:38:03,394 - DEBUG - f.futawilly.py - ln.281 - update_thread() currently testing post_num=16314009
2019-04-05 18:38:03,519 - DEBUG - f.futawilly.py - ln.281 - update_thread() currently testing post_num=16314255
2019-04-05 18:38:03,646 - DEBUG - f.futawilly.py - ln.64 - decide_if_media_redownload() image_row=<__main__.get_images_table.<locals>.Image object at 0x0000016D93FBE0B8>;
2019-04-05 18:38:03,770 - CRITICAL - f.futawilly.py - ln.553 - Unhandled exception!
2019-04-05 18:38:03,893 - ERROR - f.futawilly.py - ln.554 - 'Image' object is not subscriptable
Traceback (most recent call last):
  File "G:\Programming\bibanon\python-futawilly\futawilly.py", line 550, in <module>
    if __name__ == '__main__':
  File "G:\Programming\bibanon\python-futawilly\futawilly.py", line 543, in main
    req_ses=req_ses,
  File "G:\Programming\bibanon\python-futawilly\futawilly.py", line 412, in board_update_loop
    req_ses=req_ses,
  File "G:\Programming\bibanon\python-futawilly\futawilly.py", line 291, in update_thread
    req_ses=req_ses,
  File "G:\Programming\bibanon\python-futawilly\futawilly.py", line 94, in save_post_media
    image_row=existing_image_row
  File "G:\Programming\bibanon\python-futawilly\futawilly.py", line 65, in decide_if_media_redownload
    if (image_row['banned'] == True):# Do not save banned images.
TypeError: 'Image' object is not subscriptable
2019-04-05 18:38:04,025 - INFO - f.futawilly.py - ln.555 - Program finished.
2019-04-05 18:38:04,145 - INFO - f.futawilly.py - ln.560 - EOF